### ISSUE TITLE
Disk Types and Performance

### ISSUE THREAD

**Issue by DanielTSI** [opentelekomcloud-docs/elastic-volume-service#67]
Issue on page:        https://github.com/opentelekomcloud-docs/elastic-volume-service/blob/main/umn/source/overview/disk_types_and_performance.rst

This site does not represent the current portfolio. Please remove "High-IO Performance optimised" & "Ultra-high IO latency optimised" disk types

**Comment by marmulle2** [comment]
Hi Daniel, 
Updated UMN is corrected and visible in PREPROD helpcenter 
https://docs.otc.t-systems.com/elastic-volume-service/umn/overview/disk_types_and_performance.html#en-us-topic-0014580744

Also PD was aligned to have the same values in both documents
https://confluence.tsi-dev.otc-service.com/display/DR/OTCPR-11696-EVS-PD

**Comment by marmulle2** [comment]
Hi Daniel, 
updated documentation is available in prod Helpcenter:
You can compare UMN and PD and values are the same
UMN:
https://docs.otc.t-systems.com/elastic-volume-service/umn/overview/disk_types_and_performance.html
PD:
https://confluence.tsi-dev.otc-service.com/display/DR/OTCPR-11696-EVS-PD

 API:
https://docs.otc.t-systems.com/elastic-volume-service/api-ref/change_history.html
